# -*- coding: utf-8 -*-
from . import apala_route
from . import apala_transport_order
from . import apala_trip
from . import apala_cargo_manifest
from . import apala_freight_order
from . import apala_storage_contract
from . import apala_customs_document
from . import apala_trip_expense
from . import fleet_vehicle_extend
from . import hr_employee_extend
from . import res_partner_extend
from . import apala_config_settings
from . import apala_dashboard
from . import apala_vehicle_job_card
from . import apala_daily_vehicle_status
from . import apala_maintenance_schedule
from . import apala_fuel_log
from . import apala_driver_checklist
from . import apala_spare_part
from . import apala_customer_credit
